from typing import Union

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import pathlib


def make_drive(creds_file_path: pathlib.Path) -> object:
    """Instatiate google drive auth object.

    Args:
        creds_file_path (pathlib.Path): Path to credentials file directory.

    Returns:
        object: Google drive auth object.
    """

    gauth = GoogleAuth()

    # User must download this themselves from the GCP console
    gauth.LoadClientConfigFile(
        client_config_file=creds_file_path / "client_secrets.json"
    )

    # Generated by make_drive_creds()
    gauth.LoadCredentialsFile(credentials_file=creds_file_path / "my_creds.json")

    drive = GoogleDrive(gauth)

    return drive


def get_gdrive_ids(
    drive: object, locations: list, return_last: bool = True
) -> Union[dict, str]:
    """Get the directory ids up to and including the last file specified in the list of locations from google drive.

    Args:
        drive (object): The authenticated drive handler object.
        locations (list): The list of directories to search through.
        return_last (bool): Whether to return the full dict of location names and location ids or just the last as str.

    Returns:
        dict/str: The google drive ids of the directories specified. Or the final id of the path.
    """
    locations = locations.copy()
    file_dict = {"root": "root"}
    title = "root"
    while len(locations) > 0:
        file_list = drive.ListFile(
            {"q": f"'{file_dict[title]}' in parents and trashed=false"}
        ).GetList()
        title = locations.pop(0)
        for file in file_list:
            if file["title"] == title:
                file_dict[title] = file["id"]

    if return_last:
        return file_dict[title]  # the file id of the file you are interested in
    else:
        return file_dict  # all of the dir names and ids leading up to the file you are interested in
